version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - travel_booking_net

  mongodb:
    image: bitnami/mongodb:6.0
    environment:
      MONGODB_DATABASE: travel-bookings
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: secretPassword
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: secretPassword
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME:  localhost
      # MONGODB_ADVERTISE_IP: 127.0.0.1
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    ports:
      - 27017:27017
    networks:
      - travel_booking_net
    volumes:
      - mongo_data:/bitnami

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - travel_booking_net
    volumes:
      - redis_data:/data
      
volumes:
  mongo_data:
  rabbitmq_data:
  rabbitmq_log:
  redis_data:
    driver: local
networks:
  travel_booking_net:
    driver: bridge
